import { Providers } from '@/components/providers/providers'
import { SiteHeader } from '@/components/site-header'
import '@/styles/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <Providers>
            <SiteHeader />
            {children}
          </Providers>
      </body>
    </html>
  )
}
